[package]
name = "instascrape"
version = "0.1.0"
authors = ["jakbyte <jakbyte@gmail.com>"]
edition = "2018"

readme = "README.md"
license = "MIT"
publish = false

[dependencies]
scraper = "0.11"
reqwest = "0.9"
serenity = "0.7"